### ISSUE TITLE
Special characters are not allowed. 

### ISSUE THREAD

**Issue by columb** [chaseoes/TF2#1]
Vesion: 2.02-DEV
Error: http://pastebin.com/P8K5Tqtx
messages.yml: https://dl.dropbox.com/u/27770548/Fl2/messages.yml

**Comment by psycowithespn** [comment]
Fixed in https://github.com/chaseoes/TF2/commit/a3040214906ef2fb93424ff91f87e15cd3d6f096

**Comment by columb** [comment]
Try to load my messages.yml. There still an error.

**Comment by psycowithespn** [comment]
The error is you started a line with & without surrounding it with ' '. You could have not known this because exceptions were caught but never shown. Latest push shows the yaml errors now and disables the plugin so that one npe does not occur.
