### ISSUE TITLE
BIG PROBLEM!

### ISSUE THREAD

**Issue by Ethris** [chaseoes/TF2#10]
I'm using Your plugin about 3 months...
And I've got this problem: http://screenshooter.net/0189454/anejshv

**Comment by psycowithespn** [comment]
It would help if the screenshot was uploaded. There is nothing on that website. If it is a picture of console, just open your server.log and copy and paste the error or whatever the problem is, otherwise save a screenshot as a jpg or something and throw it on http://imgur.com/

**Comment by Ethris** [comment]
Its an error with DeathListener.. On that screenshot is error.

**Comment by Ethris** [comment]
Sorry. I'll fix that. I'll upload it on Monday.

**Comment by chaseoes** [comment]
Monday has passed.
