### ISSUE TITLE
Feature Request: More cheat prevention

### ISSUE THREAD

**Issue by tim-savage** [chaseoes/TF2#12]
I have a world dedicated to game arenas. I would like some of my admins to have creative mode in this world, so they can create new arenas and edit existing ones. Unfortunately, these same admins cheat unmercifully with any advantage given to them. So I've had to use permissions to lock down the arena world.

If this plugin prevented players from switching to creative mode and using teleport commands while in-game, I could re-allow admins creative mode in this world, without them being able to cheat while playing.

I guess the most flexible implementation would be to have a 'blocked-commands' setting, in case there are other cheating methods I've overlooked. But creative and teleport prevention could be hardcoded in the plugin, as I cannot think of any legitimate reason for players to have them during a game in progress.

Thanks!

To clarify, I've observed cheaters switching to creative mode to be able to fly, and using teleport to transport themselves directly to opponent's locations.

**Comment by chaseoes** [comment]
Revoke their tf2.create permission to remove the ability to use commands while in-game.

**Comment by tim-savage** [comment]
Good to know! I'll give that a try. Thanks again.
