### ISSUE TITLE
Could not pass event BlockBreakEvent to TF2 v2.2

### ISSUE THREAD

**Issue by orkun1675** [chaseoes/TF2#13]
This error has startup to show up very frequently: http://pastebin.com/ZcezuDd8
Tf2 version: 2.2

Could you help please?

**Comment by psycowithespn** [comment]
Do a '/tf2 debug' and paste the link here.

**Comment by orkun1675** [comment]
Here it is: http://pastebin.com/V1A9sP4R

**Comment by psycowithespn** [comment]
I would say reregister your containers. Turn your server off then wipe the containers part of the map yml. Then just redo them.
