### ISSUE TITLE
TF2 gamemodes

### ISSUE THREAD

**Issue by columb** [chaseoes/TF2#14]
Payload:
- Minecart with tnt  have to moved from A to B point
- Minecart only moves when there is a player from attacking team nearby in radius of 3 blocks
- When player moving minecart they should have affects (configurable) like Healing I.

CaptureTheFlag:
- Player with flag should have particle affect or water/lava block attached
- Dropped flag may look as red/blue wool.

KingOfTheHill:
- Same as CP but there is only 1 point
- Could be captured by both teams
- Could be recaptured by another team
- After capture have to be holded for X seconds

**Comment by chaseoes** [comment]
Other gamemodes will not be added at this time as it requires the plugin to be re-written.
