### ISSUE TITLE
TabAPI

### ISSUE THREAD

**Issue by columb** [chaseoes/TF2#15]
- Per map tab
- Show kills near playername and sort it by their amount
- Separate playernames into teams red/blue by rows

**Comment by WizardCM** [comment]
This would be better done with the scoreboard.

**Comment by columb** [comment]
@WizardCM Even full player list of ~24 players with their frags? Scoreboard is fine to show time, team scores but player list... I don't think so.

**Comment by WizardCM** [comment]
Oh that's true, I didn't think about such a large group. Hmm..

**Comment by chaseoes** [comment]
Scoreboard is now used to display kills in tab list.
