### ISSUE TITLE
Support for custom items

### ISSUE THREAD

**Issue by robotnikthingy** [chaseoes/TF2#19]
Can you make it so that it is possible for classes to use Items with custom lore or names, like weapons from the crackshot plugin?

If you want an idea on how to implement it, you could always have the player place a chest with those items a few blocks underneath the class button, and when someone hits the class button then the Items are simply copied from the chest beneath it and into the players inventory

**Comment by chaseoes** [comment]
Unfortunately, if implemented, it would be much easier to do it through the configuration. You can re-open this if you figure out a good way to implement it in that manner.

**Comment by robotnikthingy** [comment]
Well i did think of one way to do it through the config file. Many plugins with custom items offer a command which will give a player a custom item when a command is typed in, so perhaps there can be an option in the config file for a command to be ran when a class is picked. in order to prevent any kind of duplication, an option can be added that will wipe the inventory when a class is switched.

This is really the only other way at the moment i can thing of for custom items to be implemented easily, since there is no standard when it comes to custom items. the only other way would be to develop and API of some sort that would allow developers of custom item plugins to make them compatible.

Edit: actually, crackshot recently added an API so that developers can give custom items directly to players, so implementing this would be helpful
https://github.com/Shampaggon/CrackShot/wiki/Hooking-into-CrackShot
