### ISSUE TITLE
spawnpoint wrong

### ISSUE THREAD

**Issue by fungreenfox** [chaseoes/TF2#25]
![2013-05-25_15 33 44](https://f.cloud.github.com/assets/3235334/564120/39982fd2-c541-11e2-91f7-9512057b7b51.png)
Thanks for a fantastic plugin!

using TF2 V.2.3 and bukkit 2.5.2
I want to start this sethbling map with the electronic mounted also. The checkdata command shows that i do not have set the lobby wall yet, and i can't find the right way to set it.

second, when the map ends up , time-out, players are getting teleported to pos "-421 6 -567"  while red and blue teams are already set. I cant find the (id 537) box under the map, which is doing this. Can you help locate this box or how to correct it, please.

**Comment by chaseoes** [comment]
The wiki covers creating the lobby wall:
https://github.com/chaseoes/TF2/wiki/Creating-Your-First-Map

As it's not my plugin teleporting you, I can't really help with that.

**Comment by fungreenfox** [comment]
You are closing tickets very fast. I have tryed following wiki and doing the command but nothing is set?

**Comment by chaseoes** [comment]
There isn't a command to set the lobby wall, so you're doing something wrong.
