### ISSUE TITLE
lobby wall is not set

### ISSUE THREAD

**Issue by fungreenfox** [chaseoes/TF2#26]
you are closing tickets very fast.

I have been following the wiki pages and as i see, there is only one command for setting the lobby wall. 
I do point 1-8 and reach
 Create your lobby wall by placing a sign:
First Line: [TF2]
Second Line: map
Third Line: <map name>

I do so, and it says default map. The world is called teamfortress, and the map and we select is TF2.
![2013-05-25_13 38 08](https://f.cloud.github.com/assets/3235334/564130/56bd3e84-c543-11e2-8d54-52d2fcad6130.png)

do i have to set the class buttons up? the default map is working with the prebuild class buttons.

To create your lobby wall, place a single sign on a wall, formatted like this:
(two signs showed at your info page).
then it shows default.

**Comment by chaseoes** [comment]
#25
