### ISSUE TITLE
nullpointerException at changing colors

### ISSUE THREAD

**Issue by fungreenfox** [chaseoes/TF2#27]
is it supposed to do this?
Bukkit 1.5.2
TF2 2.3 

00:53:49 [INFO] Fungreenfox issued server command: /tf2 list fortress
00:54:00 [INFO] @: Set Fungreenfox's spawnpoint to -416, 34, -576
00:54:29 [SEVERE] java.lang.NullPointerException
00:54:29 [SEVERE]       at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:203)
00:54:29 [SEVERE]       at me.chaseoes.tf2.utilities.Localizer.loadPrefixedMessage(Localizer.java:24)
00:54:29 [SEVERE]       at me.chaseoes.tf2.listeners.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:76)
00:54:29 [SEVERE]       at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
00:54:29 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
00:54:29 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
00:54:29 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
00:54:29 [SEVERE]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
00:54:29 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
00:54:29 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
00:54:29 [SEVERE]       at org.bukkit.craftbukkit.v1_5_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:186)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.PlayerInteractManager.interact(PlayerInteractManager.java:370)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:631)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.Packet15Place.handle(SourceFile:58)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:109)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
00:54:29 [SEVERE]       at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by psycowithespn** [comment]
Fixed in build [#20](http://ci.chaseoes.com/job/TF2/20/)

**Comment by fungreenfox** [comment]
Thank you.
