### ISSUE TITLE
Non-OP players can't join

### ISSUE THREAD

**Issue by ghost** [chaseoes/TF2#3]
Since the latest 1.5 update non-OP players can't join the game.

**Comment by psycowithespn** [comment]
It is your permissions system that isnt updated to 1.5. (I'm assuming PermissionsEx since that is the only one I know of that breaks every minecraft update). This is all I can determine from what you have given me.

**Comment by psycowithespn** [comment]
Wait, there isn't even a Bukkit release for 1.5 yet. How are you running tf2?

**Comment by ghost** [comment]
I use GroupManager and it works fine on 1.5 with other plugins. Also, I use this Bukkit custom release: https://github.com/ProjectAres/CraftBukkit

**Comment by psycowithespn** [comment]
I am unable to compile this so I am unable to test or fix this. The only thing I can say is wait for a real CraftBukkit release.

**Comment by psycowithespn** [comment]
I should have asked this first, but are you giving your players the permission "tf2.play"?

**Comment by ghost** [comment]
Shame to hear I have to wait for a real CraftBukkit release :/. Yes, I do give my players the tf2.play permission, it worked in 1.4.7 but not in 1.5.

**Comment by psycowithespn** [comment]
Then the only things I can blame it on right now are the Craftbukkit build you are using or the interface between groupmanager and Craftbukkit because we use player.hasPermission() everywhere.

**Comment by ghost** [comment]
Welp, guess my server is offline for a few days.... Thanks for trying to help me out! :)

**Comment by chaseoes** [comment]
Dionn, I can test this and/or fix if you can manage to send me the compiled jar you have.

(Feel free to join our IRC channel, #tf2plugin on irc.esper.net).

**Comment by ghost** [comment]
Looks like TagAPI is the problem... it throws an error when I start up the server. Still weird I can still join as an OP though. I uploaded the .jar for you here: http://updo.nl/file/0ebc0ad6.jar
Thanks for the help so far :)

**Comment by ghost** [comment]
Weird, what is your permissions plugin? Plugins I use: AuthMe, Essentials,
EssentialsChat, EssentialsGroupManager, NoCheatPlus, TF2, TagAPI and
WorldEdit.

Edit: where did your comment go? I can't find it :/

2013/3/14 chaseoes notifications@github.com
