### ISSUE TITLE
TF2 Major BUG - Help Appriciated

### ISSUE THREAD

**Issue by orkun1675** [chaseoes/TF2#38]
This is happening the 3. time. It happened on 3 different builds so the build I am using here doesn't really matter. But for the records I am using latest RB which is 2.3. How I fixed the previous occasions, I don't know.. I deleted the plugin deleted all folder and installed a few days later, fresh. But the error as I can see is not dependent on the config or the setup. It happens randomly and sometimes makes Tf2 not playlabe. People entering the game can't leave can't get class items and loose their inventory/mode etc. I am bored with dealing with this issue.

Here are the errors that repeat. These repeat a thousand times in an hour. But they are always the same.

Errors:
http://pastebin.com/YvutFk8J
http://pastebin.com/eyDQVRQ2
http://pastebin.com/VbgKz6e6
http://pastebin.com/ccrd7t06
http://pastebin.com/ATLBgrsh

And finally this error which I don't think is related to TF2 but anyways:
http://pastebin.com/SSHXU1rZ

About the teleport error. This very similar error was previously caused by AuthMe and/or Minigames and they somehow fixed it after a long time. Please do check AuthMe's latest changes so you can get an idea. AuthMe Link: http://dev.bukkit.org/bukkit-mods/authme-reloaded/

If you want a full server.log (it's gonna be over 100mb because I ahve 400online) or the TF2 folder I can upload on Dropbox and send it to you.

One more thing: the recent dev builds had an flag capture issue, no one could capture the flag. I don't know if it is fixed now. I had to revert back ro RB because of that error.

My players really love this plugin so please help me on this :)

**Comment by chaseoes** [comment]
Are you using the latest build off of http://ci.chaseoes.com? We attempted to fix the issue the first time you commented about it.

**Comment by orkun1675** [comment]
Yes I tried that and then we had the flag capture issue so I downgraded. I will know upgrade test it and report back here.

**Comment by orkun1675** [comment]
Downloaded the latest build 27#

Flag capture seems fine now. I will inform you if this happens again. You may close this issue.
