### ISSUE TITLE
Use experience level to show current killstreak

### ISSUE THREAD

**Issue by columb** [chaseoes/TF2#40]
Since total amount of kills is now at scoreboard.

**Comment by orkun1675** [comment]
Isn't that used to show the capture process of flags?

**Comment by columb** [comment]
@orkun1675 
No. I mean experience level, not current exp level progress. 
![no](https://f.cloud.github.com/assets/1553489/684014/19502e62-d9ed-11e2-81e0-ae003b5defe4.png)

**Comment by chaseoes** [comment]
This will not be changed at this time.
