### ISSUE TITLE
Dedicated TF2 Server Option

### ISSUE THREAD

**Issue by kethomassen** [chaseoes/TF2#43]
Add an option in the config for your server to become dedicated to TF2. This means it will be like playing real TF2. No need to join the game with signs and stuff. You will automatically be joined when logged in.

This would benefit not only me, but hundreds of other servers. Thanks!

**Comment by chaseoes** [comment]
Added in version 2.4, 6d5e65e68f0c00d678e66ada34170b021428fc29.
