### ISSUE TITLE
Plugin Freezes when running above Spigot build 877

### ISSUE THREAD

**Issue by GaryQian** [chaseoes/TF2#44]
The plugin will freeze on the "Plugin created by chaseos" message when it is run on spigot builds 910 and 934 (recommended). It works on spigot build 877. There is a change made between Spigot 877 and Spigot 910 that breaks the plugin.

The plugin will work fine for a few games, but will then break. The only factor that impacts whether it will freeze or not is the build of spigot I use.

Please fix this, as it disables a large part of my minigames 2 server and is quite crippling as the plugin will be down for hours at a time.

In an overview: Broken on builds 910 and 934. Works on Build 877. Change made to spigot that made the plugin incompatible between 877 and 910

**Comment by GaryQian** [comment]
Oh I would like to add that the same occurs when there are no other plugins (except for Worldedit, TagAPI, and WorldGuard). It is most likely NOT an issue caused by conflicting plugins.

I will begin to try builds between 877 and 910 to narrow down the scope.

**Comment by orkun1675** [comment]
I am using Spigot 934 and I am not expriencing a freeze problem. When does the game freeze, at what stage?

**Comment by GaryQian** [comment]
Build 893 works fine. It freezes right after the game ends and the signs display the credits. It gets stuck on the credits and refused to move on.

**Comment by chaseoes** [comment]
It sounds like there should be an error in your console when this happens.

**Comment by GaryQian** [comment]
I will check for errors in the logs, but I haven't personally seen any.

**Comment by chaseoes** [comment]
No response, will assume the issue is fixed. Create a new ticket if needed.
