### ISSUE TITLE
Teleportation Issues

### ISSUE THREAD

**Issue by king-tnerb** [chaseoes/TF2#48]
This seems to be new in 1.6.2 but I'm not positive. If you do /tf2 leave it will tell you that there has been an internal error. It will tp you back out to the TF2 lobby but it will still think you are ingame. Also, at the end of a game, players will stay on the map and will not be tp'ed back to the lobby. The only solution for both of these is to uninstall and reinstall the plugin.

**Comment by psycowithespn** [comment]
Ok, I can not personally duplicate this so I will need a copy of the error that is shown in console when someone types the command and when the game ends. I will also need the link that "/tf2 debug" outputs.

**Comment by king-tnerb** [comment]
OK the /tf2 leave error returns this:

15.07 17:46:51 [Server] INFO ... 15 more
15.07 17:46:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
15.07 17:46:51 [Server] INFO at me.chaseoes.tf2.commands.CommandManager.onCommand(CommandManager.java:99)
15.07 17:46:51 [Server] INFO at me.chaseoes.tf2.commands.LeaveCommand.execLeaveCommand(LeaveCommand.java:34)
15.07 17:46:51 [Server] INFO at me.chaseoes.tf2.Game.leaveGame(Game.java:336)
15.07 17:46:51 [Server] INFO at me.chaseoes.tf2.GamePlayer.leaveCurrentGame(GamePlayer.java:169)
15.07 17:46:51 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/kitteh/tag/TagAPI
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:118)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:839)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:882)
15.07 17:46:51 [Server] INFO at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:964)
15.07 17:46:51 [Server] INFO at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
15.07 17:46:51 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
15.07 17:46:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
15.07 17:46:51 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'tf2' in plugin TF2 v2.4-b46
15.07 17:46:51 [Server] SEVERE null

And the error at the end of the game:
15.07 17:59:58 [Server] INFO at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:53)
15.07 17:59:58 [Server] INFO at me.chaseoes.tf2.capturepoints.CapturePoint$1.run(CapturePoint.java:90)
15.07 17:59:58 [Server] INFO at me.chaseoes.tf2.Game.winMatch(Game.java:229)
15.07 17:59:58 [Server] INFO at me.chaseoes.tf2.Game.stopMatch(Game.java:165)
15.07 17:59:58 [Server] INFO at me.chaseoes.tf2.GamePlayer.leaveCurrentGame(GamePlayer.java:169)
15.07 17:59:58 [Server] INFO java.lang.NoClassDefFoundError: org/kitteh/tag/TagAPI
15.07 17:59:58 [Server] WARNING Task #206 for TF2 v2.4-b46 generated an exception
15.07 17:59:58 [Server] INFO The red team has won on the map tf2!

**Comment by psycowithespn** [comment]
Ok, I also need the link that "/tf2 debug" outputs.

**Comment by king-tnerb** [comment]
http://pastebin.com/XWGnkpRQ

**Comment by psycowithespn** [comment]
Update TagAPI. Or use scoreboards with no TagAPI.
