### ISSUE TITLE
Lobby Wall Bug?

### ISSUE THREAD

**Issue by matt-dolio** [chaseoes/TF2#50]
I'm trying to make the lobby wall since I've done everythin else, and when I try to make it, it posts on it: /tf2 checkdata dustbowl and also puts it in my chat, and it says inthe command that the one thing I haven't done is make a lobby wall, which is what I'm trying to do but it won't let me, so it's an endless loop of "nope". Please help!

**Comment by chaseoes** [comment]
Post a screenshot of the output of /tf2 checkdata?

**Comment by chaseoes** [comment]
Failed to provide additional information.
