### ISSUE TITLE
New Permission "tf2.join.sign"

### ISSUE THREAD

**Issue by orkun1675** [chaseoes/TF2#51]
I have a multi world server which consists of 7 worlds. On each world players have different inventories, different minigames, pvp rights etc. If I give the tf2.join permission to my players then they can use this command all across the server to escape pvp or cause inventory bugs. (I can't disable tf2 join command in all regions using WG because I got thousands of regions.)

I would really like to see one of these 2 enchantments to solve my issue;
1. Split the join permission to "tf2.join.sign" and "tf2.join.command" so I can force my users to right click on a sign. 
2. Check the user world and the arena world when tf2 join command is executed. Give an error if the user is not in the same world.

Thanks!

**Comment by chaseoes** [comment]
What about a flag on the __global__ region?

**Comment by orkun1675** [comment]
Well if the region itself has a blocked-cmds flag it overrides the global region. So I would have to add this to almost all regions.

**Comment by Relicum** [comment]
orkun1675 easy solution http://dev.bukkit.org/bukkit-plugins/perworldplugins/ especially if you have a single server with many large plugins. If not ask me on skype and i'll code it for in and submit a pull request.

**Comment by chaseoes** [comment]
Added tf2.join.sign permission.
