### ISSUE TITLE
Encountered an error while trying to update the lobby wall

### ISSUE THREAD

**Issue by Dniel97** [chaseoes/TF2#55]
I have the newest version of TagApi (2.7.1) and the newest Team Fortress 2 version (TF2 2.4)my CraftBukkit Server (CraftBukkit Beta: 1.7.2-R0.2). And every seconds my console says: "[TF2] Encountered an error while trying to update the lobby wall." This ist since CraftBukkit 1.7.2.

**Comment by chaseoes** [comment]
Re-create your lobby wall.

**Comment by Dniel97** [comment]
I sneak and destroyed the signs and I re-created the lobby wall but this doesn't work! :(
And the cature points are missing.
![2014-01-05_18 45 01](https://f.cloud.github.com/assets/6324072/1847062/6c5c3174-7631-11e3-9e03-302eaf2267ed.png)
