### ISSUE TITLE
Class Buttons Broken and Leave Issues

### ISSUE THREAD

**Issue by nathan-pajamasoft** [chaseoes/TF2#56]
1. When any player tries to leave, it doesn't have them leave. It just teleports them to the lobby. When they try to join another game it will just say that they are still in a game!
2. Some default classes, when the button is pushed, will say unknown class when, for sure, it is a known class. The classes are: Scout, Medic, Spy, Pyro.
3. If you have a bow in lobby, your arrows will get used up even though the arrows don't come out.

**Comment by chaseoes** [comment]
Cannot reproduce.

**Comment by nathan-pajamasoft** [comment]
?

**Comment by nathan-pajamasoft** [comment]
Helpful o_o
