### ISSUE TITLE
Can't Leave, Classes Not Working

### ISSUE THREAD

**Issue by nathan-pajamasoft** [chaseoes/TF2#57]
1. When you type /tf2 leave, it teleports you to the lobby you set, but if you try to rearange your inventory or try to join another game, it says that you are still in the game.
2. Classes Medic, Pyro, Scout, and I think sniper, when the button is right-clicked, will not give you your items, saying unknown class.

I have already reported this but have gotten no reply of getting it fixed! Please take it into mind to fix your plugin!

**Comment by chaseoes** [comment]
The classes Medic, Pyro, Scout do not exist as default classes.

**Comment by nathan-pajamasoft** [comment]
They were on the list by default, though.

**Comment by nathan-pajamasoft** [comment]
I didn't add them
