### ISSUE TITLE
Can't Leave

### ISSUE THREAD

**Issue by nathan-pajamasoft** [chaseoes/TF2#58]
Ok, please do not just close this and think nothing of it. It is a bug in your game, and I can't play on it without this fix! When you leave, it doesn't actually leave you. It just says that you are still in a game (both when you leave and when game is over)!

**Comment by chaseoes** [comment]
Unable to reproduce.

**Comment by ghost** [comment]
I Just Created A Similar Issue With A New Post With Pastebin Error Logs.
