### ISSUE TITLE
Fix ScoreBoard and new options.

### ISSUE THREAD

**Issue by RafaelPL** [chaseoes/TF2#62]
I'm using your plugin since 2 years. And I need help. If you wish to add: 
- [x] Commands that are to be performed after the killing. 
- [x] Commands that are to be performed after a point. 
- [x] More permissions. tf2.map. <name> tf2.class.spy
- [x] On the scoreboard add control points that have been taken or not. 
- [x] Add commands that can run the game. 
- [x] Prizes for individual teams.
- [x] Limit classes (eg 2 spies on map) (configuration) 

Fix scoreboard. If a player leaves the game and joins the server again. Scoreboard crashes and minecraft to crash ... 
Sorry for my English but ...: D

And please update GIT HUB.

**Comment by RafaelPL** [comment]
Update:
Fix clone items.

**Comment by chaseoes** [comment]
Added per-class permissions.

**Comment by chaseoes** [comment]
Added commands to be performed for killing and point capturing.

**Comment by chaseoes** [comment]
Added class limits. Everything else won't be fixed.
