### ISSUE TITLE
TagAPI has a new event, update to it

### ISSUE THREAD

**Issue by mbax** [chaseoes/TF2#63]
New event documentation [here](http://kittehorg.github.io/TagAPI/apidocs/org/kitteh/tag/AsyncPlayerReceiveNameTagEvent.html). Ensure any calls in the event are threadsafe.

**Comment by chaseoes** [comment]
TagAPI support removed, addressed in 9be3f0c13f262299f5bce5f03a22d15c0d7a8baf.
