### ISSUE TITLE
[BUG] [Important] Item IDs

### ISSUE THREAD

**Issue by TacticalCactupi** [chaseoes/TF2#64]
Hello, I recently installed TF2 and CrackShot, a gun plugin. It uses different items IDs, and some with colons. So, for example, some guns are different inks. So, I went about adding the items with the ",", like so:     - 351,3.1, but instead of returning the desired item, it would give the item 351:0. Why is this? And how can I correctly give items like 351:3?

**Comment by chaseoes** [comment]
Class system completely changed in b80cb6e8e0704cd19424074b6340a5ba667a731e.
