### ISSUE TITLE
New Permission Nodes, Ideas, More Donator Support

### ISSUE THREAD

**Issue by Ryguyl21** [chaseoes/TF2#67]
Hey chaseoes I was just wondering if maybe there could be a part implemented into the TF2 plugin were donors can join full games, I've had lot's of people on my server saying they want more added to the donation ranks I literally added everything from flying in lobby's, to pets, I even went to getting a custom trails plugin done. I just don't know what do do for them any more! I want to keep them all happy yet I've added everything I can think about. so maybe if the plugin could get new permission nodes, like join full games, Donor's can choose their team? or can start a private match with friends on side maps? I don't know I'm just jotting down ideas! if any of this could be implemented it would make my life a whole lot easier!

Thanks, Ryguyl21

**Comment by Ryguyl21** [comment]
Anyone?

**Comment by JellyBellyFred** [comment]
Sounds good! Hope they add this.

**Comment by chaseoes** [comment]
Added tf2.joinfull and tf2.pickteam permissions.

**Comment by JellyBellyFred** [comment]
Cool thanks!
