### ISSUE TITLE
Big List Of Bugs, And Ideas

### ISSUE THREAD

**Issue by ghost** [chaseoes/TF2#68]
# 
# BUGS:

-DEBUG FILE: http://pastebin.com/jTcgceGm
-STARTUP LOG: http://pastebin.com/GfgjKv51
- Everytime I Break A Pressure Plate: http://pastebin.com/HvBUkZ47
- Everytime I Use /tf2 delete: http://pastebin.com/2Gv7xEZM
- Everytime I Use /tf2 Leave In A Lobby: http://pastebin.com/f45rqfiR
- Everytime I Leave In The Middle Of A Game: http://pastebin.com/BcMTNaP1
# 
# IDEAS:
- If It Hasn't Been Stated Clearly Over The Other Ideas, Perhaps Command Binding To The Buttons As Well.
- Please, Incorporate CrackShot Support For Selecting Classes.  Like For Each Class, You Can Add Commands. Like /shot get soldier.
- Add Support From Disguisecraft To Enable Disguising With Commands For Specific Classes, Eg: Add Option In Each Class: 

CONFIG VIEW BETA:

Classes:
. Scout:
   .allow_disguisecraft_disguising: true/false
     .allow_block_disguising: true/false
     . block_disguise_blacklist: block ids
   .allow_mob_disguising: true/false
     .mod_disguise_blacklist: mob list
   .allow_player_disguise: true/false
     .player_disguise_blacklist: players
- Add Ability To Bind Commands To Some Of The Class Items:

CONFIG VIEW BETA:

 .267.DAMAGE_ALL.1
 .commands: true/false
   Right_click_commands:
  .  command1
  .  command2
  .left_click_commands:
  .  command1
  .  command2

**Comment by chaseoes** [comment]
Would the ability to bind commands to classes be sufficient for adding CrackShot support?

**Comment by ghost** [comment]
it probably would be, i was just saying otherwise just in case there was a better way to incorporate it in. the crackshot plugin gives you the desired weapon with /shot get <name> or /shot give <player> <name> <amount>

**Comment by chaseoes** [comment]
Unable to reproduce the bugs, no plans on implementing the features (though the new class system may have added CrackShot support).
