### ISSUE TITLE
Player Killed Self?

### ISSUE THREAD

**Issue by ghost** [chaseoes/TF2#69]
Players who die see a message saying "Killed by ...." and that person is themselves!

Also Player kill counts do not increment.

Note I am using factions and have a warzone setup for the TF2 map, Is there anything I can do to avoid conflicts between mods? (Im guessing that is what it is)

**Comment by chaseoes** [comment]
Unable to reproduce.

**Comment by ghost** [comment]
Using mcpc 1.6.4 build 262 - is this an issue for them?

If it is can you possibly assist them with fixing - give me some info on why this may occur so I can pass it along?

**Comment by ghost** [comment]
Mcpc support allows for use of flans mod guns - this makes tf2 insanely awesome to pla y
