### ISSUE TITLE
Potions still turning into water bottles

### ISSUE THREAD

**Issue by xIGBClutchIx** [chaseoes/TF2#7]
Potions are currently still turning into water bottles in the latest update.
Fix: https://github.com/lbjdaking23/TF2/commit/f3e39c66b5f09b2ad0188c5a28dc65d3cc869a39

**Comment by psycowithespn** [comment]
Fixed in https://github.com/chaseoes/TF2/commit/dcd4524d07c7ad1030f6ff9edd10eefb2cfc8fb2
