### ISSUE TITLE
Class removal

### ISSUE THREAD

**Issue by FlippantCactus** [chaseoes/TF2#86]
Now classes are removed from the config.yml, where do they get read from if at all?

**Comment by chaseoes** [comment]
Class chests.

```
/tf2 create classchest <class name>
```

https://github.com/chaseoes/TF2/blob/b80cb6e8e0704cd19424074b6340a5ba667a731e/src/main/java/com/chaseoes/tf2/commands/CreateCommand.java#L112

**Comment by FlippantCactus** [comment]
Thanks, missed it
