### ISSUE TITLE
AutoStart for TF2

### ISSUE THREAD

**Issue by LIFEKASH** [chaseoes/TF2#87]
How do I make it so that it auto starts?

**Comment by Permanently** [comment]
You'll have to go through the source to add that. There isn't currently a feature that does that (i don't think there is, idk though)

**Comment by chaseoes** [comment]
Yes there is. It automatically starts after the lobby is at least 50% full. This is configurable in the configuration, as seen here:

https://github.com/chaseoes/TF2/blob/master/src/main/resources/config.yml#L3

Please don't spread misinformation.
