### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by remypas** [chaseoes/TF2#9]
Would it be possible to grant the winning team a reward?
Say, a specified amount of a specified item for each team member of the winning team?

**Comment by JustinFatalx** [comment]
I would like this also.

**Comment by chaseoes** [comment]
Would adding the ability to have console commands run when a team wins be adequate? For example, giving each player on the winning team 3 diamonds:

```
run-commands-on-win:
  - give %player diamond 3
```
